export const colorOptions = [
    { value: 'red', label: 'Red' },
    { value: 'orange', label: 'Orange' },
    { value: 'yellow', label: 'Yellow' },
    { value: 'lime', label: 'Lime' },
    { value: 'green', label: 'Green' },
    { value: 'teal', label: 'Teal' },
    { value: 'sky', label: 'Sky' },
    { value: 'blue', label: 'Blue' },
    { value: 'violet', label: 'Violet' },
    { value: 'fuchsia', label: 'Fuchsia' },
  ]

  export const staticLabels = [
    {
      modpackId: 'placeholder',
      name: "Modpack",
      imageUrl: "https://unsplash.it/1000",
      color: 'white',
      voteCount: 0,
      commentCount: 0,
    },
    {
      modpackId: 'placeholder',
      name: "Modpack",
      imageUrl: "https://unsplash.it/1000",
      color: 'white',
      voteCount: 0,
      commentCount: 0,
    },
    {
      modpackId: 'placeholder',
      name: "Modpack",
      imageUrl: "https://unsplash.it/1000",
      color: 'white',
      voteCount: 0,
      commentCount: 0,
    },
    {
      modpackId: 'placeholder',
      name: "Modpack",
      imageUrl: "https://unsplash.it/1000",
      color: 'white',
      voteCount: 0,
      commentCount: 0,
    },
    {
      modpackId: 'placeholder',
      name: "Modpack",
      imageUrl: "https://unsplash.it/1000",
      color: 'white',
      voteCount: 0,
      commentCount: 0,
    },
    {
      modpackId: 'placeholder',
      name: "Modpack",
      imageUrl: "https://unsplash.it/1000",
      color: 'white',
      voteCount: 0,
      commentCount: 0,
    },
    {
      modpackId: 'placeholder',
      name: "Modpack",
      imageUrl: "https://unsplash.it/1000",
      color: 'white',
      voteCount: 0,
      commentCount: 0,
    },
    {
      modpackId: 'placeholder',
      name: "Modpack",
      imageUrl: "https://unsplash.it/1000",
      color: 'white',
      voteCount: 0,
      commentCount: 0,
    },
    {
      modpackId: 'placeholder',
      name: "Modpack",
      imageUrl: "https://unsplash.it/1000",
      color: 'white',
      voteCount: 0,
      commentCount: 0,
    },
    {
      modpackId: 'placeholder',
      name: "Modpack",
      imageUrl: "https://unsplash.it/1000",
      color: 'white',
      voteCount: 0,
      commentCount: 0,
    }
  
  ];