export const colorOptions = [
  { value: "red", label: "Red" },
  { value: "orange", label: "Orange" },
  { value: "yellow", label: "Yellow" },
  { value: "lime", label: "Lime" },
  { value: "green", label: "Green" },
  { value: "teal", label: "Teal" },
  { value: "sky", label: "Sky" },
  { value: "blue", label: "Blue" },
  { value: "violet", label: "Violet" },
  { value: "fuchsia", label: "Fuchsia" },
];

export const bgColorVariants: Record<string, string> = {
  red: "bg-red-400",
  orange: "bg-orange-400",
  yellow: "bg-yellow-400",
  lime: "bg-lime-400",
  teal: "bg-teal-400",
  green: "bg-green-400",
  blue: "bg-blue-400",
  violet: "bg-violet-400",
  fuchsia: "bg-fuchsia-400",
  sky: "bg-sky-400",
};
export const borderColorVariants: Record<string, string> = {
  red: "border-red-400",
  orange: "border-orange-400",
  yellow: "border-yellow-400",
  lime: "border-lime-400",
  teal: "border-teal-400",
  green: "border-green-400",
  blue: "border-blue-400",
  violet: "border-violet-400",
  fuchsia: "border-fuchsia-400",
  sky: "border-sky-400",
};
export const textColorVariants: Record<string, string> = {
  red: "text-red-400",
  orange: "text-orange-400",
  yellow: "text-yellow-400",
  lime: "text-lime-400",
  teal: "text-teal-400",
  green: "text-green-400",
  blue: "text-blue-400",
  violet: "text-violet-400",
  fuchsia: "text-fuchsia-400",
  sky: "text-sky-400",
};

export const staticLabels = [
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
];

export const placeholderDetails = {
  color: "grey",
  name: "Modpackss",
  comments: [
    {
      username: "Placeholder",
      comment: "This is a placeholder comment",
      timestamp: 0,
      discord_id: "0",
      avatar_url: "a",
    },
  ],
  description: "This is a placeholder description",
  galleryImages: [
    {
      imageUrl: "/placeholderImg.png",
    },
  ],
  imageUrl: "/placeholderImg.png",
  isSponsored: false,
  modpackId: "placeholder",
  officialUrl: "https://www.trainjumper.com",
  suggestedBy: "Placeholder",
  tags: ["placeholder", "placeholder"],
  timesVoted: 0,
  voteCount: 0,
  isArchived: false,
  isPublished: true,
};
