export const colorOptions = [
  { value: "red", label: "Red" },
  { value: "orange", label: "Orange" },
  { value: "yellow", label: "Yellow" },
  { value: "lime", label: "Lime" },
  { value: "green", label: "Green" },
  { value: "teal", label: "Teal" },
  { value: "sky", label: "Sky" },
  { value: "blue", label: "Blue" },
  { value: "violet", label: "Violet" },
  { value: "fuchsia", label: "Fuchsia" },
];

export const staticLabels = [
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
];

export const placeholderDetails = {
  name: "Modpack",
  imageUrl: "/src/assets/placeholderImg.png",
  color: "grey",
  description: "This is a placeholder description",
  timesVoted: 0,
  voteCount: 0,
  comments: [
    {
      username: "Placeholder",
      comment: "This is a placeholder comment",
      timestamp: 0,
      discord_id: "0",
      avatar_url: "a",
    },
  ],
};
