export const colorOptions = [
  { value: "red", label: "Red" },
  { value: "orange", label: "Orange" },
  { value: "yellow", label: "Yellow" },
  { value: "lime", label: "Lime" },
  { value: "green", label: "Green" },
  { value: "teal", label: "Teal" },
  { value: "sky", label: "Sky" },
  { value: "blue", label: "Blue" },
  { value: "violet", label: "Violet" },
  { value: "fuchsia", label: "Fuchsia" },
];

export const staticLabels = [
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
  {
    modpackId: "placeholder",
    name: "Modpack",
    imageUrl: "/src/assets/placeholderImg.png",
    color: "white",
    voteCount: 0,
    commentCount: 0,
  },
];

export const placeholderDetails = {
  color: "grey",
  name: "Modpackss",
  comments: [
    {
      username: "Placeholder",
      comment: "This is a placeholder comment",
      timestamp: 0,
      discord_id: "0",
      avatar_url: "a",
    },
  ],
  description: "This is a placeholder description",
  galleryImages: [
    {
      imageUrl: "/placeholderImg.png",
    },
  ],
  imageUrl: "/placeholderImg.png",
  isSponsored: false,
  modpackId: "placeholder",
  officialUrl: "https://www.trainjumper.com",
  suggestedBy: "Placeholder",
  tags: ["placeholder", "placeholder"],
  timesVoted: 0,
  voteCount: 0,
  isArchived: false,
  isPublished: true,
};
